name: Build

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight
  workflow_dispatch:  # Allows manual triggering of the workflow
  push:
    branches:
      - Adding-JavaDocs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find all jar files in home directory
        run: find ~ -type f -name \*.jar || true

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Cache Python packages
        uses: actions/cache/restore@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python

      - name: Cache BuildTools
        uses: actions/cache/restore@v4
        with:
          path: ~/BuildTools
          key: ${{ runner.os }}-BuildTools

      - name: Cache Maven packages
        uses: actions/cache/restore@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven

      - name: Set up all required JDKs
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # Use 'zulu' or another distribution if needed
          java-version: |
            8
            11
            16
            17
            18
            19
            21

      - name: Install Python dependencies
        run: |
          pip install -U requests beautifulsoup4

      - name: Run Python build script
        run: |
          python .github/create_javadocs_jar_file.py

      - name: Add new jar files to the repository
        run: |
          git config --local user.name "GitHub Workflow"
          git config --local user.email "workflow@github.com"

          git add jar_files/
          git commit -m "Added new Javadocs files"
          git push

      - name: Post Cache Python packages
        if: always()
        uses: actions/cache/save@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python

      - name: Post Cache BuildTools
        if: always()
        uses: actions/cache/save@v4
        with:
          path: ~/BuildTools
          key: ${{ runner.os }}-BuildTools

      - name: Post Cache Maven packages
        if: always()
        uses: actions/cache/save@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven
